# Generated by Django 5.0.6 on 2024-05-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
