# Generated by Django 5.0.6 on 2024-05-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=100)),
                ('receipt', models.FileField(upload_to='')),
                ('trip_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.tripdetail')),
            ],
        ),
    ]
