# Generated by Django 5.0.6 on 2024-05-30 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.expensedetail')),
            ],
        ),
    ]
