# Generated by Django 5.0.6 on 2024-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('tripId', models.CharField(max_length=100)),
                ('viewsCnt', models.IntegerField()),
                ('contentId', models.CharField(max_length=100)),
            ],
        ),
    ]
