# Generated by Django 5.0.6 on 2024-05-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_border'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='작성자',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
