# Generated by Django 5.0.6 on 2024-05-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_border_작성자_alter_review_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='조회수',
            field=models.IntegerField(default=0),
        ),
    ]
