# Generated by Django 5.0.6 on 2024-05-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_border_조회수'),
    ]

    operations = [
        migrations.AlterField(
            model_name='border',
            name='작성자',
            field=models.CharField(max_length=255),
        ),
    ]
