# Generated by Django 5.0.6 on 2024-05-30 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_delete_review_remove_border_댓글수_border_trip'),
        ('trips', '0002_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='border',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='border',
            name='작성자',
        ),
        migrations.RemoveField(
            model_name='border',
            name='제목',
        ),
        migrations.AddField(
            model_name='border',
            name='trip_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trips.tripdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='border',
            name='이미지',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='border',
            name='내용',
            field=models.TextField(null=True),
        ),
    ]
