# Generated by Django 5.0.6 on 2024-05-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_remove_border_내용_remove_border_좋아요_border_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='border',
            name='제목',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
