# Generated by Django 5.0.6 on 2024-05-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_border_제목'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='border',
            name='hashtag',
        ),
    ]
