# Generated by Django 5.0.6 on 2024-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
