# Generated by Django 5.0.6 on 2024-05-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_tripdetail_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='hashtag',
        ),
    ]
