# Generated by Django 5.0.6 on 2024-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0005_remove_tripdetail_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="symbol/"),
        ),
    ]
