# Generated by Django 5.0.6 on 2024-06-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_region_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
